//This file is automatically generated. DO NOT EDIT!
using System;
using RobotRaconteur;
using System.Collections.Generic;

#pragma warning disable 0108

namespace sensors.ati.mini45
{
public class FTData
{
    public long time;
    public double[] ft_data;
}

[RobotRaconteurServiceObjectInterface()]
public interface ATImini45Host
{
    ATImini45 get_ft(int ind);
}

[RobotRaconteurServiceObjectInterface()]
public interface ATImini45
{
    double[] wrench { get; set; }
    byte recording_data { get; set; }
    void changeCalibration(byte config);
    void bias();
    void startRecordingData(string filename);
    void stopRecordingData();
    Pipe<FTData> FTDataStream{ get; set; }
}

}
